name: Deploy n8n Workflows

on:
  push:
    branches:
      - main  # This will run the pipeline every time you push to 'main'
  pull_request:
    branches:
      - main  # This will run the pipeline when you open a PR to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build the Docker image for n8n
      - name: Build n8n Docker image
        run: |
          docker build -t n8n-app .

      # Optional: You can add tests for your workflows here if needed
      # - name: Run tests
      #   run: docker run n8n-app some-test-script

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 3: Checkout code again to make sure everything is up to date
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 4: Deploy to your server
      - name: Deploy to n8n instance (Docker)
        run: |
          # Replace with your actual deployment logic, e.g. SSH into your server and pull the image
          ssh user@your-server-ip "docker pull n8nio/n8n:latest && docker-compose down && docker-compose up -d"
