name: Deploy n8n Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build n8n Docker image
        run: docker build -t n8n-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Changed to match your secret name

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "echo 'Connected!'"
        env:
          EC2_HOST: 52.215.250.161

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
          # Docker setup
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker

          # Cleanup existing container
          sudo docker stop n8n || true
          sudo docker rm n8n || true

          # Run n8n
          sudo docker run -d \
            --name n8n \
            -p 5678:5678 \
            -v ~/.n8n:/root/.n8n \
            -e N8N_HOST=$EC2_HOST \
            n8nio/n8n:latest
          EOF
        env:
          EC2_HOST: 52.215.250.161
